[http.routers.squeaky-knees]
  entryPoints = ["web"]
  rule = "Host(`squeakyknees.blog`,`www.squeakyknees.blog`)"
  middlewares = ["https-redirect"]
  service = "squeaky-knees"

[http.routers.squeaky-knees-secure]
  entryPoints = ["websecure"]
  rule = "Host(`squeakyknees.blog`,`www.squeakyknees.blog`)"
  service = "squeaky-knees"
  [http.routers.squeaky-knees-secure.tls]
    certResolver = "letsencrypt"

[http.middlewares.https-redirect.redirectScheme]
  scheme = "https"

[http.services.squeaky-knees.loadBalancer]
  [[http.services.squeaky-knees.loadBalancer.servers]]
    url = "http://squeaky_knees_web:8000"
