[api]
  insecure = false
  debug = false

[log]
  level = "INFO"

[entryPoints.web]
  address = ":80"

[entryPoints.websecure]
  address = ":443"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  watch = true

[certificatesResolvers.letsencrypt]
  [certificatesResolvers.letsencrypt.acme]
    email = "noreply@squeakyknees.blog"
    storage = "/letsencrypt/acme.json"
    [certificatesResolvers.letsencrypt.acme.httpChallenge]
      entryPoint = "web"
