[api]
  insecure = false
  debug = false

[log]
  level = "ERROR"

[entryPoints.web]
  address = ":80"

[entryPoints.websecure]
  address = ":443"

[certificatesResolvers.letsencrypt]
  [certificatesResolvers.letsencrypt.acme]
    email = "your-email@example.com"
    storage = "/letsencrypt/acme.json"
    [certificatesResolvers.letsencrypt.acme.httpChallenge]
      entryPoint = "web"
